version: 2

builds:
  - main: ./cmd/main.go
    binary: dk
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: dk
    homepage: https://github.com/abroudoux/dk
    repository:
      owner: abroudoux
      name: homebrew-tap
    commit_author:
      name: abroudoux
      email: arthur.broudoux@gmail.com

checksum:
  name_template: "checksums.txt"
