FROM golang:1.22.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /dk ./cmd/main.go

FROM ubuntu:20.04

RUN apt update -y && apt upgrade -y && apt install git -y

COPY --from=builder /dk /dk

RUN ln -s /dk /usr/bin/dk

CMD ["tail", "-f", "/dev/null"]
